version: '3.4'

services:
  mysql-server:
    image: mysql:5.6
    restart: always
    stop_grace_period: 1m
    environment:
      TZ: 'Europe/Helsinki'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'burpui'
      MYSQL_DATABASE: 'burpui'
      MYSQL_PASSWORD: 'mysqlpasswd'
    volumes:
      - ./burp-server/mysql:/var/lib/mysql

  redis-server:
    image: redis
    restart: always
    environment:
      TZ: 'Europe/Helsinki'
    volumes:
      - ./burp-server/redis:/data

  burp-server:
    image: burp-server
    # emails are sent from this hostname
    hostname: burp.domain.tld
    environment:
      TZ: 'Europe/Helsinki'
      NOTIFY_SUCCESS: 'true'
      NOTIFY_FAILURE: 'true'
      NOTIFY_EMAIL: 'youremail@example.com'
      #SMTP_RELAY: 'smtp.domain.tld'
      #SMTP_PORT: '587'
      #SMTP_AUTH: 'username:password'
      #SMTP_TLS: 'yes'
      REDIS: 'true'
      REDIS_SERVER: 'redis-server'
      REDIS_PORT: '6379'
      MYSQL: 'true'
      MYSQL_HOST: 'mysql-server'
      MYSQL_USER: 'burpui'
      MYSQL_DATABASE: 'burpui'
      MYSQL_PASSWORD: 'mysqlpasswd'
      # restorepath needs to have slashes escaped
      RESTOREPATH: '\/tmp\/bui'
      BUI_USER: 'bui'
      BUI_USER_PASSWORD: 'buipasswd'
      WEBUI_ADMIN_PASSWORD: 'admin'
    restart: unless-stopped
    stop_grace_period: 1m
    stdin_open: true
    tty: true
    ports:
      - "4971:4971"
      - "4972:4972"
      - "5000:5000"
    volumes:
      - ./burp-server/conf:/etc/burp
      - ./burp-server/backups:/var/spool/burp
      - ./burp-server/restore:/var/spool/restore
      - ./burp-server/logs:/var/log/burp-ui
    links:
      - mysql-server
      - redis-server
